### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by richard-yin** [ThatOneReaper/minecraft-PortalMod#5]
Start writing JSON files for blocks per 1.8 spec, starting with BlockBasicPortal

http://www.wuppy29.com/minecraft/1-8-tutorial/updating-1-7-to-1-8-part-3-basic-blocks

**Comment by abujaki** [comment]
Began work on json files. Presently each code block makes a different file. It can be found in [this gist](https://gist.github.com/abujaki21/c4be510f38d0ee673293)

Will review and wait for folder structure update before commit

**Comment by abujaki** [comment]
Update on branch _working_ commit e9deb55e1eac8646fa7ddc0b1c5338f9ce2bb175 for review

**Comment by abujaki** [comment]
Commit 3e4218a216635d053a9c59c98afafb16fc018704 requires all instances of "portalBasic" to be changed to "teleporterSpawn", including filenames

**Comment by richard-yin** [comment]
JSON autogen can be found here: http://www.wuppy29.com/minecraft/json-generator/

**Comment by abujaki** [comment]
blocks and items properly rendering
